apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
nameSuffix: -alpha

commonLabels:
  project: ecommerce-app
  tier: backend
  env: dev

commonAnnotations:
  team: finance
  maintainer: "ryan.nograles@gmail.com"
  repository: "git-repo"

images:
  - name: nginx
    newTag: "1.27.1"

replicas:
  - name: nginx
    count: 2

resources:
  - ../../base
