name: key-value-app
services:
  backend:
    container_name: key-value-backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.key-val.db
    environment:
      - MONGODB_HOST=db
      - PORT=3000
    depends_on:
      - db
    networks:
      - key-value-network
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
  db:
    container_name: mongodb
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    ports:
      - "27017:27017"
    env_file:
      - .env.root.db
      - .env.key-val.db
    volumes:
      - type: bind
        source: ./db-config/mongo-init.js
        target: /docker-entrypoint-initdb.d/mongo-init.js
        read_only: true
      - type: volume
        source: mongodb-data
        target: /data/db
    networks:
      - key-value-network

volumes:
  mongodb-data:

networks:
  key-value-network:
    