apiVersion: v1
kind: Service
metadata:
  name: color-api-clusterip-svc
  labels:
    app: color-api
spec:
  type: ClusterIP
  selector:
    app: color-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
