apiVersion: v1
kind: Service
metadata:
  name: color-api-nodeport-svc
  labels:
    app: color-api
spec:
  type: NodePort
  selector:
    app: color-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
